### PR TITLE
remove 'require "jasmine" in rake file. this kills new deck's wagn seed

### PR DESCRIPTION
**Pull request by chuenlok**

### CODE REVIEW

**Comment by xithan** [comment]
Noticed this too today and took care of it here: https://github.com/wagn/wagn/pull/304
Don't we need this gem anymore? I removed it only for non-developer decks.

**Comment by chuenlok** [comment]
we need this gem(for core or mod-dev)  but I don't think we need it in Rakefile?

**Comment by xithan** [comment]
Does `rake spec:javascript` work without it?

**Comment by chuenlok** [comment]
I tried in my local and it works without `require 'jasmine'`

**Comment by ethn** [comment]
if we can get things working with this elsewhere, that would be preferable, imo.  Seems out of place here.

Would it be possible to put this in a task file, for example?

**Comment by ethn** [comment]
Sorry, just saw Henry's previous comment.  Obviously, if it works without it, that's even better!

**Pull request merged**
