### PR TITLE
Generator

### PR DESCRIPTION
**Pull request by GerryG**
Re-created

### CODE REVIEW

**Comment by GerryG** [comment]
Another random failure?  Haven't seen that one before.

**Comment by ethn** [comment]
I don't actually know what this branch is about.  Is there a ticket or issue or something somewhere?

I was assuming it might be a smaller diff to the card-gem branch, but I can't really go hunting through 2000+ changed files.  Shall I just wait until that's merged?

**Comment by GerryG** [comment]
Sorry, see this one for the additional changes on top of card-gem: https://github.com/GerryG/wagn/pull/43

It needs some work yet because the API isn't quite what we would want.   One goal is to get the generators working more in sync with rails so you see the added ones in the help messages.  The other goal is to cover the case of generating a card model into an existing rails app.  That isn't quite what I would like to have yet.

If all or most of this becomes 'stuff we need' to complete card-gems, then the main purpose of this branch is to separate some of the work from the already huge PR on card-gem

**Comment by GerryG** [comment]
The steps changed.  They seemed to pull in steps I had on my build for test purposes.  I get no gear wheel on these builds.  Did someone copy my steps manually?

**Comment by ethn** [comment]
Gerry, I'm a little confused by all the different PR's / comments on this one, but would you be willing to:
1. open a new PR to the new wagn/1_15 branch
2. paste the most valuable comments over there
3. close all the other PR's

?

**Comment by GerryG** [comment]
Yes, we can do that.  The most relevant comments should still be on the 'virtual' PR between this branch and card-gem (within my fork of wagn).  Once we have an integrated 1_15 branch, we can move the important comments to a new PR to that branch.

To summarize, this branch will be all about updating the developer command line api for the cards within an app case.  I'll need your input to make sure this is right.

**Pull request closed without merging**
